include("${CMAKE_CURRENT_LIST_DIR}/MoltenVKVersion.cmake")
set(mvk_version_header "${VITA3K_IOS_MOLTENVK_INCLUDE_DIR}/MoltenVK/mvk_private_api.h")
if(NOT EXISTS "${mvk_version_header}")
    message(FATAL_ERROR "Missing MoltenVK version header: run cmake -P .ci/install-moltenvk.cmake (add -DMVK_PACKAGE=simulator for Simulator)")
endif()
file(READ "${mvk_version_header}" mvk_header)
foreach(component MAJOR MINOR PATCH)
    if(NOT mvk_header MATCHES "#define[ \t]+MVK_VERSION_${component}[ \t]+([0-9]+)")
        message(FATAL_ERROR "Cannot read MoltenVK ${component} version from ${mvk_version_header}")
    endif()
    set(mvk_${component} "${CMAKE_MATCH_1}")
endforeach()
set(mvk_detected "${mvk_MAJOR}.${mvk_MINOR}.${mvk_PATCH}")
if(NOT mvk_detected VERSION_EQUAL VITA3K_MOLTENVK_VERSION)
    message(FATAL_ERROR "Expected MoltenVK ${VITA3K_MOLTENVK_VERSION}, found ${mvk_detected}. Reinstall the pinned package with cmake -P .ci/install-moltenvk.cmake (add -DMVK_PACKAGE=simulator for Simulator).")
endif()
message(STATUS "iOS MoltenVK headers: ${mvk_detected}")
